# Generated by Django 3.2.7 on 2021-11-23 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offGrounds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='pub_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
