# Generated by Django 3.2.7 on 2021-09-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offGrounds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=2000)),
                ('year', models.CharField(max_length=2000)),
            ],
        ),
    ]
