# Generated by Django 3.2.7 on 2021-11-23 03:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offGrounds', '0002_auto_20211122_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='listing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='offGrounds.listing'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 23, 3, 13, 1, 479425, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 23, 3, 13, 1, 479425, tzinfo=utc)),
        ),
    ]
