# Generated by Django 3.2.7 on 2021-11-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offGrounds', '0002_alter_listing_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='pub_date',
            field=models.DateTimeField(default=0.0),
        ),
    ]
