# Generated by Django 3.2.7 on 2021-11-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offGrounds', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='year',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
