# Generated by Django 3.2.7 on 2021-11-23 03:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offGrounds', '0003_auto_20211122_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='listing',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='listing',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 23, 3, 14, 20, 20713, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 23, 3, 14, 20, 20713, tzinfo=utc)),
        ),
    ]
