# Generated by Django 3.2.7 on 2021-11-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offGrounds', '0003_auto_20211101_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.TextField(max_length=2000)),
                ('address', models.TextField(max_length=2000)),
                ('bed', models.BigIntegerField(default=0)),
                ('bath', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('area', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
    ]
