# Generated by Django 3.2.7 on 2021-11-23 03:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offGrounds', '0003_alter_listing_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='place',
            field=models.TextField(default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
