# Generated by Django 3.2.7 on 2021-11-03 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offGrounds', '0004_pins'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pins',
            new_name='Pin',
        ),
    ]
