# Generated by Django 3.2.7 on 2021-11-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offGrounds', '0004_auto_20211122_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='place',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(max_length=2000),
        ),
    ]
