# Generated by Django 3.2.7 on 2021-11-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offGrounds', '0005_auto_20211123_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(default=0.0),
        ),
    ]
