# Generated by Django 3.2.7 on 2021-11-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offGrounds', '0005_rename_pins_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='address',
        ),
        migrations.AlterField(
            model_name='pin',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
