# Generated by Django 3.2.7 on 2021-11-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offGrounds', '0006_auto_20211103_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pin',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
