# Generated by Django 3.2.7 on 2021-11-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offGrounds', '0007_auto_20211103_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('num_beds', models.IntegerField(default=0)),
                ('num_baths', models.FloatField(default=0.0)),
                ('rent', models.FloatField(default=0.0)),
                ('size', models.FloatField(default=0.0)),
            ],
        ),
    ]
