# Generated by Django 3.2.7 on 2021-11-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offGrounds', '0008_listing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pin',
        ),
        migrations.AddField(
            model_name='listing',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='listing',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
