# Generated by Django 3.2.7 on 2021-11-30 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offGrounds', '0010_remove_review_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='offGrounds.listing'),
        ),
    ]
