# Generated by Django 3.2.7 on 2021-11-07 20:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offGrounds', '0011_alter_listing_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='picture',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='listing',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 20, 53, 21, 368998, tzinfo=utc)),
        ),
    ]
