# Generated by Django 3.2.7 on 2021-12-02 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offGrounds', '0011_alter_review_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.TextField(default='N/A')),
                ('phone_number', models.CharField(default='000-000-0000', max_length=12)),
                ('instagram', models.CharField(default='N/A', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='offGrounds.user')),
            ],
        ),
    ]
