# Generated by Django 3.2.7 on 2021-11-07 20:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offGrounds', '0012_auto_20211107_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='picture',
        ),
        migrations.AlterField(
            model_name='listing',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 20, 56, 59, 473291, tzinfo=utc)),
        ),
    ]
