# Generated by Django 3.2.7 on 2021-12-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offGrounds', '0012_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='posted_by',
            field=models.CharField(default='anonymous', max_length=200),
        ),
    ]
