# Generated by Django 3.2.7 on 2021-11-08 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offGrounds', '0005_auto_20211103_1820'),
        ('offGrounds', '0012_alter_listing_pub_date'),
    ]

    operations = [
    ]
