# Generated by Django 3.2.7 on 2021-12-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offGrounds', '0012_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.TextField(blank=True, null=True),
        ),
    ]
