# Generated by Django 3.2.7 on 2021-11-07 20:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offGrounds', '0013_auto_20211107_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 20, 57, 48, 656060, tzinfo=utc)),
        ),
    ]
