# Generated by Django 3.2.7 on 2021-11-08 06:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offGrounds', '0013_auto_20211108_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='fitness',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='laundry',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='parking',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, default='project-b-16\\media\\images\\Image_Coming_Soon.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 6, 51, 4, 676809, tzinfo=utc)),
        ),
    ]
