# Generated by Django 3.2.7 on 2021-11-08 06:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offGrounds', '0014_auto_20211108_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='project-b-16\\media\\images\\Image_Coming_Soon.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 6, 53, 9, 288253, tzinfo=utc)),
        ),
    ]
