# Generated by Django 3.2.7 on 2021-11-17 23:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offGrounds', '0015_auto_20211108_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.TextField(default='Year'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='fitness',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='laundry',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='parking',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 23, 40, 33, 690327, tzinfo=utc)),
        ),
    ]
