# Generated by Django 3.2.7 on 2021-11-07 21:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offGrounds', '0015_alter_listing_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='picture',
            field=models.ImageField(default='project-b-16/offGrounds/images/Image_Coming_Soon.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='listing',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 21, 4, 47, 793389, tzinfo=utc)),
        ),
    ]
