# Generated by Django 3.2.7 on 2021-11-15 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offGrounds', '0013_merge_20211108_0213'),
        ('offGrounds', '0015_auto_20211108_0153'),
    ]

    operations = [
    ]
