# Generated by Django 3.2.7 on 2021-11-17 23:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offGrounds', '0016_auto_20211117_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 23, 48, 12, 208366, tzinfo=utc)),
        ),
    ]
