# Generated by Django 3.2.7 on 2021-11-15 21:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offGrounds', '0017_auto_20211115_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AlterField(
            model_name='listing',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 15, 21, 44, 32, 373569, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 15, 21, 44, 32, 373569, tzinfo=utc)),
        ),
    ]
