# Generated by Django 3.2.7 on 2021-11-17 23:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offGrounds', '0017_alter_listing_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 23, 56, 21, 352244, tzinfo=utc)),
        ),
    ]
