# Generated by Django 3.2.7 on 2021-11-22 19:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offGrounds', '0025_auto_20211122_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='profile',
        ),
        migrations.AlterField(
            model_name='listing',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 19, 41, 14, 255678, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 22, 19, 41, 14, 255678, tzinfo=utc)),
        ),
    ]
